version: 2.1
orbs:
  node: circleci/node@5.0.1
  #Orbs are packages for different functionalities in circleCI
  #Orbs are integration library to help CircleCI works its other toolchain
jobs: #jobs within pipeline
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
